# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SAP-WAS-SOAP
version:      0.05
version_from: lib/SAP/WAS/SOAP.pm
installdirs:  site
requires:
    SOAP::Lite:                    0.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
